SmtpPort: 25
TelegramBotToken: SPECIFY THERE TELEGRAM BOT TOKEN
Routing:
    Route:
        Email: SPECIFY THERE E-MAIL ADDRESS
        TelegramChatId: SPECIFY THERE TELEGRAM CHATID
Logging:
  LogLevel:
    Default: Debug
